
CREATE TABLE achados (
	id INT PRIMARY KEY AUTO_INCREMENT,
	titulo VARCHAR(255) NOT NULL,
	descricao TEXT NOT NULL,
	tipo VARCHAR(255) NOT NULL,
	categoria VARCHAR(255) NOT NULL,
	local TEXT NOT NULL,
	quem TEXT NOT NULL,
	data VARCHAR(255) NOT NULL,
	foto LONGBLOB NOT NULL
);

CREATE TABLE perdidos (
	id INT PRIMARY KEY AUTO_INCREMENT,
	titulo VARCHAR(255) NOT NULL,
	descricao TEXT NOT NULL,
	tipo VARCHAR(255) NOT NULL,
	categoria VARCHAR(255) NOT NULL,
	local TEXT NOT NULL,
	quem TEXT NOT NULL,
	data VARCHAR(255) NOT NULL,
	foto LONGBLOB NOT NULL
);
